name: "Submit a News Item"
description: "Propose a News post"
title: "[News] "
labels: ["submission:news"]
body:
  - type: input
    id: title
    attributes:
      label: Title
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: Date (YYYY-MM-DD)
      placeholder: "2026-03-01"
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - announcement
        - updates
        - field-notes
        - in-the-news
        - ideas
        - admin
        - qa
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary (1–3 sentences)
    validations:
      required: true

  - type: textarea
    id: body
    attributes:
      label: Body (markdown ok)
    validations:
      required: true

  - type: input
    id: thumb
    attributes:
      label: Thumbnail URL (optional)
      placeholder: "https://..."
    validations:
      required: false
