name: "Submit an Event"
description: "Propose a CHAMP calendar event"
title: "[Event] "
labels: ["submission:event"]
body:
  - type: input
    id: title
    attributes:
      label: Event title
      placeholder: "North Shore Foray + ID Workshop"
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: Date (YYYY-MM-DD)
      placeholder: "2026-03-14"
    validations:
      required: true

  - type: input
    id: time
    attributes:
      label: Time (24h, optional)
      placeholder: "13:00"
    validations:
      required: false

  - type: input
    id: location
    attributes:
      label: Location
      placeholder: "Ipswich River Wildlife Sanctuary"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: "What are we doing? Who’s it for?"
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Link (optional)
      placeholder: "https://..."
    validations:
      required: false

  - type: input
    id: contact
    attributes:
      label: Contact (optional)
      placeholder: "Discord @name / email"
    validations:
      required: false
