name: "Submit a Link"
description: "Suggest a resource for the Links page"
title: "[Link] "
labels: ["submission:link"]
body:
  - type: input
    id: title
    attributes:
      label: Link title
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: URL
      placeholder: "https://..."
    validations:
      required: true

  - type: input
    id: category
    attributes:
      label: Category
      placeholder: "Community / Education / Tools / Research"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description (optional)
    validations:
      required: false
